### ISSUE TITLE
Throw error on all make commands

### ISSUE THREAD

**Issue by tobz-nz** [ahuggins/open-on-make#18]
I'm getting this error for all artisan `make` commands:

```
[2018-09-06 03:13:17] local.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "name" argument does not exist. in /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/symfony/console/Input/Input.php:110
Stack trace:
#0 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/ahuggins/open-on-make/src/Listeners/OpenOnMake.php(68): Symfony\Component\Console\Input\Input->getArgument('name')
#1 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/ahuggins/open-on-make/src/Listeners/OpenOnMake.php(45): OpenOnMake\Listeners\OpenOnMake->filename(Object(Illuminate\Console\Events\CommandFinished))
#2 [internal function]: OpenOnMake\Listeners\OpenOnMake->handle(Object(Illuminate\Console\Events\CommandFinished))
#3 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(379): call_user_func_array(Array, Array)
#4 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Illuminate\\Cons...', Array)
#5 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(182): Illuminate\Events\Dispatcher->dispatch('Illuminate\\Cons...', Array, false)
#6 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Illuminate\Events\Dispatcher->fire(Object(Illuminate\Console\Events\CommandFinished))
#7 /Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/tobyevans/Code/dovetailx/api.dovetailx/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
```

Laravel 5.6

**Comment by tobz-nz** [comment]
Ah I see (after actually looking into it).
I think its when I run `--help` without filling it in args. Will PR a fix inna sec.

**Comment by ahuggins** [comment]
PR submitted, fixes issue.
